import React from 'react'
import Cards from './Cards';

const doma = [
    {
        id: '1',
        title: 'Проект дома ДБ023',
        floor: '1',
        sizes: '8x7 м',
        square: '55.4 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'есть',
        previewImg: require('../images/Projects/db023/db023_01.webp'),
        planImg: require('../images/Projects/db023/db023_11.webp')
    },
    {
        id: '2',
        title: 'Проект дома ДБ024',
        floor: '1+М',
        sizes: '8x7 м',
        square: '84.2 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db024/db024_01.webp')
    },
    {
        id: '3',
        title: 'Проект дома ДБ037',
        floor: '1+М',
        sizes: '9x6 м',
        square: '86.5 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db037/db037_01.webp')
    },
    {
        id: '4',
        title: 'Проект дома ДБ058',
        floor: '1+М',
        sizes: '8.5x7 м',
        square: '92.7 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db058/db058_01.webp')
    },
    {
        id: '5',
        title: 'Проект дома ДБ066',
        floor: '1.5',
        sizes: '8x8 м',
        square: '112 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '2',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db066/db066_01.webp')
    },
    {
        id: '6',
        title: 'Проект дома ДБ073',
        floor: '1.5',
        sizes: '7x6 м',
        square: '70.3 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '3',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db073/db073_01.webp')
    },
    {
        id: '7',
        title: 'Проект дома ДБ127',
        floor: '2',
        sizes: '',
        square: '71.9 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db127/db127_01.webp')
    },
    {
        id: '8',
        title: 'Проект дома ДБ128',
        floor: '1',
        sizes: '',
        square: '69 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'вальмовая',
        kukushka: 'нет',
        twoDoor: 'есть',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db128/db128_01.webp')
    },
    {
        id: '9',
        title: 'Проект дома ДБ129',
        floor: '1+М',
        sizes: '',
        square: '63.6 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'есть',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db129/db129_01.webp')
    },
    {
        id: '10',
        title: 'Проект дома ДБ135',
        floor: '1+М',
        sizes: '8x6 м',
        square: '69,3 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '0',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db135/db135_01.webp')
    },
    {
        id: '11',
        title: 'Проект дома ДБ174',
        floor: '1,5',
        sizes: '8x8 м',
        square: '96,2 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db174/db174_01.webp')
    },
    {
        id: '12',
        title: 'Проект дома ДБ181',
        floor: '1,5',
        sizes: '9x7 м',
        square: '107,1 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '2',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'есть',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db181/db181_01.webp')
    },
    {
        id: '13',
        title: 'Проект дома ДБ188',
        floor: '1,5',
        sizes: '10x8 м',
        square: '141,5 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db188/db188_01.webp')
    },
    {
        id: '14',
        title: 'Проект дома ДБ212',
        floor: '1',
        sizes: '15x8 м',
        square: '115,9 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '3',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg: require('../images/Projects/db212/db212_01.webp')
    },
]

function CardList() {
    return (
      <>
        {doma.map((res) =>
            <Cards key={res.id} id={res.id} title={res.title} sizes={res.sizes} square={res.square} previewImg={res.previewImg}/>
        )}
      </>
    );
  }

export default CardList