import React from 'react'
import { LinkContainer } from 'react-router-bootstrap'
import Cards from './Cards';
import Modal from './Modal';

const doma = [
    {
        id: '1',
        title: 'Проект дома ДБ023',
        floor: '1',
        sizes: '8x7 м',
        square: '55.4 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'есть',
        previewImg1: require('../images/Projects/db023/db023_01.webp'),
        previewImg2: require('../images/Projects/db023/db023_02.webp'),
        planImg1: require('../images/Projects/db023/db023_11.webp'),
        previewImg31: require('../images/Projects/db023/db023_31.webp'),
        previewImg32: require('../images/Projects/db023/db023_32.webp'),
        previewImg33: require('../images/Projects/db023/db023_33.webp'),
        previewImg34: require('../images/Projects/db023/db023_34.webp'),
    },
    {
        id: '2',
        title: 'Проект дома ДБ024',
        floor: '1+М',
        sizes: '8x7 м',
        square: '84.2 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db024/db024_01.webp'),
        previewImg2: require('../images/Projects/db024/db024_02.webp'),
        planImg1: require('../images/Projects/db024/db024_11.webp'),
        planImg2: require('../images/Projects/db024/db024_12.webp'),
        previewImg31: require('../images/Projects/db024/db024_31.webp'),
        previewImg32: require('../images/Projects/db024/db024_32.webp'),
        previewImg33: require('../images/Projects/db024/db024_33.webp'),
        previewImg34: require('../images/Projects/db024/db024_34.webp'),
    },
    {
        id: '3',
        title: 'Проект дома ДБ037',
        floor: '1+М',
        sizes: '9x6 м',
        square: '86.5 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db037/db037_01.webp'),
        previewImg2: require('../images/Projects/db037/db037_02.webp'),
        planImg1: require('../images/Projects/db037/db037_11.webp'),
        planImg2: require('../images/Projects/db037/db037_12.webp'),
        previewImg31: require('../images/Projects/db037/db037_31.webp'),
        previewImg32: require('../images/Projects/db037/db037_32.webp'),
        previewImg33: require('../images/Projects/db037/db037_33.webp'),
        previewImg34: require('../images/Projects/db037/db037_34.webp'),
    },
    {
        id: '4',
        title: 'Проект дома ДБ058',
        floor: '1+М',
        sizes: '8.5x7 м',
        square: '92.7 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db058/db058_01.webp'),
        previewImg2: require('../images/Projects/db058/db058_02.webp'),
        planImg1: require('../images/Projects/db058/db058_11.webp'),
        planImg2: require('../images/Projects/db058/db058_12.webp'),
        previewImg31: require('../images/Projects/db058/db058_31.webp'),
        previewImg32: require('../images/Projects/db058/db058_32.webp'),
        previewImg33: require('../images/Projects/db058/db058_33.webp'),
        previewImg34: require('../images/Projects/db058/db058_34.webp'),
    },
    {
        id: '5',
        title: 'Проект дома ДБ066',
        floor: '1.5',
        sizes: '8x8 м',
        square: '112 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '2',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db066/db066_01.webp'),
        previewImg2: require('../images/Projects/db066/db066_02.webp'),
        planImg1: require('../images/Projects/db066/db066_11.webp'),
        planImg2: require('../images/Projects/db066/db066_12.webp'),
        previewImg31: require('../images/Projects/db066/db066_31.webp'),
        previewImg32: require('../images/Projects/db066/db066_32.webp'),
        previewImg33: require('../images/Projects/db066/db066_33.webp'),
        previewImg34: require('../images/Projects/db066/db066_34.webp'),
    },
    {
        id: '6',
        title: 'Проект дома ДБ073',
        floor: '1.5',
        sizes: '7x6 м',
        square: '70.3 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '3',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: 'нет',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db073/db073_01.webp'),
        previewImg2: require('../images/Projects/db073/db073_02.webp'),
        planImg1: require('../images/Projects/db073/db073_11.webp'),
        planImg2: require('../images/Projects/db073/db073_12.webp'),
        previewImg31: require('../images/Projects/db073/db073_31.webp'),
        previewImg32: require('../images/Projects/db073/db073_32.webp'),
        previewImg33: require('../images/Projects/db073/db073_33.webp'),
        previewImg34: require('../images/Projects/db073/db073_34.webp'),
    },
    {
        id: '7',
        title: 'Проект дома ДБ127',
        floor: '2',
        sizes: '',
        square: '71.9 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db127/db127_01.webp'),
        previewImg2: require('../images/Projects/db127/db127_02.webp'),
        planImg1: require('../images/Projects/db127/db127_11.webp'),
        planImg2: require('../images/Projects/db127/db127_12.webp'),
        previewImg31: require('../images/Projects/db127/db127_31.webp'),
        previewImg32: require('../images/Projects/db127/db127_32.webp'),
        previewImg33: require('../images/Projects/db127/db127_33.webp'),
        previewImg34: require('../images/Projects/db127/db127_34.webp'),
    },
    {
        id: '8',
        title: 'Проект дома ДБ128',
        floor: '1',
        sizes: '',
        square: '69 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'вальмовая',
        kukushka: 'нет',
        twoDoor: 'есть',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db128/db128_01.webp'),
        previewImg2: require('../images/Projects/db128/db128_02.webp'),
        planImg1: require('../images/Projects/db128/db128_11.webp'),
        previewImg31: require('../images/Projects/db128/db128_31.webp'),
        previewImg32: require('../images/Projects/db128/db128_32.webp'),
        previewImg33: require('../images/Projects/db128/db128_33.webp'),
        previewImg34: require('../images/Projects/db128/db128_34.webp'),
    },
    {
        id: '9',
        title: 'Проект дома ДБ129',
        floor: '1+М',
        sizes: '',
        square: '63.6 кв.м',
        balkon: 'нет',
        terrace: 'нет',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'есть',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db129/db129_01.webp'),
        previewImg2: require('../images/Projects/db129/db129_02.webp'),
        planImg1: require('../images/Projects/db129/db129_11.webp'),
        planImg2: require('../images/Projects/db129/db129_12.webp'),
        previewImg31: require('../images/Projects/db129/db129_31.webp'),
        previewImg32: require('../images/Projects/db129/db129_32.webp'),
        previewImg33: require('../images/Projects/db129/db129_33.webp'),
        previewImg34: require('../images/Projects/db129/db129_34.webp'),
    },
    {
        id: '10',
        title: 'Проект дома ДБ135',
        floor: '1+М',
        sizes: '8x6 м',
        square: '69,3 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '0',
        bedroom: '2',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db135/db135_01.webp'),
        previewImg2: require('../images/Projects/db135/db135_02.webp'),
        planImg1: require('../images/Projects/db135/db135_11.webp'),
        planImg2: require('../images/Projects/db135/db135_12.webp'),
        previewImg31: require('../images/Projects/db135/db135_31.webp'),
        previewImg32: require('../images/Projects/db135/db135_32.webp'),
        previewImg33: require('../images/Projects/db135/db135_33.webp'),
        previewImg34: require('../images/Projects/db135/db135_34.webp'),
    },
    {
        id: '11',
        title: 'Проект дома ДБ174',
        floor: '1,5',
        sizes: '8x8 м',
        square: '96,2 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db174/db174_01.webp'),
        previewImg2: require('../images/Projects/db174/db174_02.webp'),
        planImg1: require('../images/Projects/db174/db174_11.webp'),
        planImg2: require('../images/Projects/db174/db174_12.webp'),
        previewImg31: require('../images/Projects/db174/db174_31.webp'),
        previewImg32: require('../images/Projects/db174/db174_32.webp'),
        previewImg33: require('../images/Projects/db174/db174_33.webp'),
        previewImg34: require('../images/Projects/db174/db174_34.webp'),
    },
    {
        id: '12',
        title: 'Проект дома ДБ181',
        floor: '1,5',
        sizes: '9x7 м',
        square: '107,1 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'нет',
        erker: 'нет',
        sanuzel: '2',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'есть',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db181/db181_01.webp'),
        previewImg2: require('../images/Projects/db181/db181_02.webp'),
        planImg1: require('../images/Projects/db181/db181_11.webp'),
        planImg2: require('../images/Projects/db181/db181_12.webp'),
        previewImg31: require('../images/Projects/db181/db181_31.webp'),
        previewImg32: require('../images/Projects/db181/db181_32.webp'),
        previewImg33: require('../images/Projects/db181/db181_33.webp'),
        previewImg34: require('../images/Projects/db181/db181_34.webp'),
    },
    {
        id: '13',
        title: 'Проект дома ДБ188',
        floor: '1,5',
        sizes: '10x8 м',
        square: '141,5 кв.м',
        balkon: 'есть',
        terrace: 'есть',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '4',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db188/db188_01.webp'),
        previewImg2: require('../images/Projects/db188/db188_02.webp'),
        planImg1: require('../images/Projects/db188/db188_11.webp'),
        planImg2: require('../images/Projects/db188/db188_12.webp'),
        previewImg31: require('../images/Projects/db188/db188_31.webp'),
        previewImg32: require('../images/Projects/db188/db188_32.webp'),
        previewImg33: require('../images/Projects/db188/db188_33.webp'),
        previewImg34: require('../images/Projects/db188/db188_34.webp'),
    },
    {
        id: '14',
        title: 'Проект дома ДБ212',
        floor: '1',
        sizes: '15x8 м',
        square: '115,9 кв.м',
        balkon: 'нет',
        terrace: 'есть',
        krylco: 'есть',
        erker: 'нет',
        sanuzel: '1',
        bedroom: '3',
        roof: 'прямая',
        kukushka: 'нет',
        twoDoor: 'нет',
        garage: '',
        topochnaya: 'нет',
        previewImg1: require('../images/Projects/db212/db212_01.webp'),
        previewImg2: require('../images/Projects/db212/db212_02.webp'),
        planImg1: require('../images/Projects/db212/db212_11.webp'),
        previewImg31: require('../images/Projects/db212/db212_31.webp'),
        previewImg32: require('../images/Projects/db212/db212_32.webp'),
        previewImg33: require('../images/Projects/db212/db212_33.webp'),
        previewImg34: require('../images/Projects/db212/db212_34.webp'),
    },
]

function CatalogBlock() {

  return (
    <>
        <div className="custom__container catalog__block">
            <div className="catalog__top__content">
                <div className="catalog__left__content">
                    <div className="catalog__left__content__title">
                        <div className="catalog__left__content__title__number">
                            50+
                        </div>
                        <div className="catalog__left__content__title__text">
                            домов из бруса
                        </div>
                    </div>
                    <div className="catalog__left__content__text">
                        Вы можете использовать как референс к будущему дому, наши архитекторы 
                        доработают проект индивидуально под потребности вашей семьи!
                    </div>
                </div>
                <div className="catalog__right__content">
                    <div className="catalog__right__content__text">
                        <div className="catalog__right__content__text__title">
                            Не хотите смотреть типовые проекты?
                        </div>
                        <div className="catalog__right__content__text__text">
                            Получите презентацию где подробно описаны все этапы нашей работы и примеры 
                            готовых индивидуальные домов за 2021 год 
                        </div>
                        <div className="catalog__right__content__text__button">
                            <Modal text="Получить презентацию"/>
                        </div>
                    </div>
                    <div className="catalog__right__content__img">

                    </div>
                </div>
            </div>
            <div className="catalog__bottom__content">
                <div className="catalog__cards">
                {doma.slice(0,3).map((res) =>
                    <Cards key={res.id} id={'built/' + res.id} title={res.title} sizes={res.sizes} square={res.square} previewImg={res.previewImg1}/>
                )}
                </div>
                <LinkContainer to="built"><div className="catalog__button main__button outline__button">
                    Посмотреть все работы
                </div></LinkContainer>
            </div>
        </div>
    </>
  )
}

export default CatalogBlock